# Generated by Django 5.2.2 on 2025-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
